import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { AppProvider } from "@/shared/reducers/GlobalState";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LT Next App",
  description: "Generated by LT next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <NextUIProvider>{children}</NextUIProvider>
        </AppProvider>
      </body>
    </html>
  );
}
