import type { Metadata } from "next";
import "../styles/globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { AppProvider } from "@/shared/reducers/GlobalState";
import { Suspense } from "react";
import { NavigationEvents } from "@/components/Navigations";
import CustomNavbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "LT Next App",
  description: "Generated by LT next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-w-[320px] flex flex-col overscroll-none p-4 bg-red-500`}
      >
        <AppProvider>
          <NextUIProvider>
            <CustomNavbar />
            {children}
            <Suspense fallback={null}>
              <NavigationEvents />
            </Suspense>
          </NextUIProvider>
        </AppProvider>
      </body>
    </html>
  );
}
